Repository tremorlabs/tremor, pull requests merged in 2022-11, with the labels that each got.

#173 build: postcss upgrade for storybook
  .storybook/main.js
  .storybook/preview.js
  package.json
Labels: dependency

#199 feat: add show cutout prop
  src/components/chart-elements/DonutChart/DonutChart.tsx
  src/stories/chart-elements/DonutChart.stories.tsx
Labels: enhancement

#163 feat: dynamic x and y axis for area, bar and line charts
  src/components/chart-elements/AreaChart/AreaChart.tsx
  src/components/chart-elements/BarChart/BarChart.tsx
  src/components/chart-elements/LineChart/LineChart.tsx
  src/components/chart-elements/common/BaseChartProps.tsx
  src/stories/chart-elements/AreaChart.stories.tsx
  src/stories/chart-elements/BarChart.stories.tsx
  src/stories/chart-elements/LineChart.stories.tsx
Labels: enhancement

#206 feat: component enhancements Datepicker, Charts, BarList, Buttons
  .storybook/preview.js
  package-lock.json
  package.json
  src/assets/DoubleArrowLeftHeadIcon.tsx
  src/assets/DoubleArrowRightHeadIcon.tsx
  src/assets/LoadingSpinner.tsx
  src/assets/index.ts
  src/components/chart-elements/AreaChart/AreaChart.tsx
  src/components/chart-elements/BarChart/BarChart.tsx
  src/components/chart-elements/DonutChart/DonutChart.tsx
  src/components/chart-elements/LineChart/LineChart.tsx
  src/components/chart-elements/common/BaseChartProps.tsx
  src/components/input-elements/Button/Button.tsx
  src/components/input-elements/ButtonInline/ButtonInline.tsx
  src/components/input-elements/Datepicker/Datepicker.tsx
  src/components/input-elements/Datepicker/utils.tsx
  src/components/layout-elements/Modal/Modal.tsx
  src/components/vis-elements/BarList/BarList.tsx
  src/components/vis-elements/DeltaBar/DeltaBar.tsx
  src/lib/inputTypes.ts
  src/lib/shape.ts
  src/stories/chart-elements/AreaChart.stories.tsx
  src/stories/chart-elements/BarChart.stories.tsx
  src/stories/chart-elements/DonutChart.stories.tsx
  src/stories/chart-elements/LineChart.stories.tsx
  src/stories/input-elements/Button.stories.tsx
  src/stories/input-elements/ButtonInline.stories.tsx
  src/stories/input-elements/Datepicker.stories.tsx
  src/stories/vis-elements/BarList.stories.tsx
Labels: work in progress, released on @beta-1.2.0
