Repository tremorlabs/tremor, pull requests merged in 2023-07, with the labels that each got.

#508 feat: Enable to clear state in Single Select component
  src/components/input-elements/Select/Select.tsx
  src/stories/input-elements/Select.stories.tsx
Labels: Type: Feature

#519 feat: add number input and email/url types to text input
  src/assets/MinusIcon.tsx
  src/assets/PlusIcon.tsx
  src/assets/index.ts
  src/components/input-elements/BaseInput.tsx
  src/components/input-elements/NumberInput/NumberInput.tsx
  src/components/input-elements/NumberInput/index.ts
  src/components/input-elements/TextInput/TextInput.tsx
  src/components/input-elements/index.ts
  src/stories/input-elements/NumberInput.stories.tsx
  src/stories/input-elements/TextInput.stories.tsx
  src/styles.css
  src/tests/input-elements/NumberInput.test.tsx
  src/tests/input-elements/TextInput.test.tsx
Labels: Type: Feature, PR: Documentation Needed, PR: In Review

#561 feat: add monotone to CurveType
  src/lib/inputTypes.ts
Labels: Type: Enhancement, PR: Documentation Needed, PR: In Review

#586 feat: add scatter chart with basic tooltip and axis value formatters
  src/components/chart-elements/ScatterChart/ScatterChart.tsx
  src/components/chart-elements/ScatterChart/ScatterChartTooltip.tsx
  src/components/chart-elements/ScatterChart/index.tsx
  src/components/chart-elements/common/utils.ts
  src/components/chart-elements/index.ts
  src/stories/chart-elements/ScatterChart.stories.tsx
  src/stories/chart-elements/helpers/testDataScatterChart.tsx
Labels: PR: In Review

#513 feat: Enable year navigation for DateRangePicker component
  src/components/input-elements/Calendar/Calendar.tsx
  src/components/input-elements/Calendar/NavButton.tsx
  src/components/input-elements/DatePicker/DatePicker.tsx
  src/components/input-elements/DateRangePicker/DateRangePicker.tsx
  src/stories/input-elements/DatePicker.stories.tsx
  src/stories/input-elements/DateRangePicker.stories.tsx
Labels: Type: Feature
