Repository tremorlabs/tremor, pull requests merged in 2023-05, with the labels that each got.

#459 fix: ISSUE-458 Make removeValueFromArray a pure function
  src/lib/utils.tsx
Labels: Type: Bug

#466 feat(daterange): allow clear on selected daterange
  .gitignore
  src/components/input-elements/DateRangePicker/DateRangePicker.tsx
  src/components/input-elements/DateRangePicker/DateRangePickerButton.tsx
  src/stories/input-elements/DateRangePicker.stories.tsx
Labels: Type: Feature

#450 fix: add `displayName` to anonymous components
  .eslintrc
  src/components/chart-elements/AreaChart/AreaChart.tsx
  src/components/chart-elements/BarChart/BarChart.tsx
  src/components/chart-elements/DonutChart/DonutChart.tsx
  src/components/chart-elements/LineChart/LineChart.tsx
  src/components/icon-elements/Badge/Badge.tsx
  src/components/icon-elements/BadgeDelta/BadgeDelta.tsx
  src/components/icon-elements/Icon/Icon.tsx
  src/components/input-elements/Button/Button.tsx
  src/components/input-elements/DateRangePicker/DateRangePicker.tsx
  src/components/input-elements/Dropdown/Dropdown.tsx
  src/components/input-elements/Dropdown/DropdownItem.tsx
  src/components/input-elements/MultiSelectBox/MultiSelectBox.tsx
  src/components/input-elements/MultiSelectBox/MultiSelectBoxItem.tsx
  src/components/input-elements/SelectBox/SelectBox.tsx
  src/components/input-elements/SelectBox/SelectBoxItem.tsx
  src/components/input-elements/Tab/Tab.tsx
  src/components/input-elements/Tab/TabList.tsx
  src/components/input-elements/TextInput/TextInput.tsx
  src/components/input-elements/Toggle/Toggle.tsx
  src/components/input-elements/Toggle/ToggleItem.tsx
  src/components/layout-elements/Accordion/Accordion.tsx
  src/components/layout-elements/Accordion/AccordionBody.tsx
  src/components/layout-elements/Accordion/AccordionHeader.tsx
  src/components/layout-elements/Accordion/AccordionList.tsx
  src/components/layout-elements/Card/Card.tsx
  src/components/layout-elements/Divider/Divider.tsx
  src/components/layout-elements/Flex/Flex.tsx
  src/components/layout-elements/Grid/Col.tsx
  src/components/layout-elements/Grid/Grid.tsx
  src/components/list-elements/List/List.tsx
  src/components/list-elements/List/ListItem.tsx
  src/components/list-elements/Table/Table.tsx
  src/components/list-elements/Table/TableBody.tsx
  src/components/list-elements/Table/TableCell.tsx
  src/components/list-elements/Table/TableHead.tsx
  src/components/list-elements/Table/TableHeaderCell.tsx
  src/components/list-elements/Table/TableRow.tsx
  src/components/text-elements/Bold/Bold.tsx
  src/components/text-elements/Callout/Callout.tsx
  src/components/text-elements/Italic/Italic.tsx
  src/components/text-elements/Legend/Legend.tsx
  src/components/text-elements/Metric/Metric.tsx
  src/components/text-elements/Subtitle/Subtitle.tsx
  src/components/text-elements/Text/Text.tsx
  src/components/text-elements/Title/Title.tsx
  src/components/util-elements/Modal/Modal.tsx
  src/components/util-elements/Tooltip/Tooltip.tsx
  src/components/vis-elements/BarList/BarList.tsx
  src/components/vis-elements/CategoryBar/CategoryBar.tsx
  src/components/vis-elements/DeltaBar/DeltaBar.tsx
  src/components/vis-elements/MarkerBar/MarkerBar.tsx
  src/components/vis-elements/ProgressBar/ProgressBar.tsx
  src/components/vis-elements/RangeBar/RangeBar.tsx
  src/components/vis-elements/Tracker/Tracker.tsx
Labels: Type: Enhancement

#448 fix: replace the `p` tag inside buttons with `span`
  src/components/input-elements/Button/Button.tsx
Labels: Type: Fix

#475 feat: add in a 'No data' message to components
  src/components/chart-elements/AreaChart/AreaChart.tsx
  src/components/chart-elements/BarChart/BarChart.tsx
  src/components/chart-elements/DonutChart/DonutChart.tsx
  src/components/chart-elements/LineChart/LineChart.tsx
  src/components/chart-elements/common/BaseChartProps.tsx
  src/components/chart-elements/common/NoData.tsx
  src/stories/chart-elements/AreaChart.stories.tsx
  src/stories/chart-elements/BarChart.stories.tsx
  src/stories/chart-elements/DonutChart.stories.tsx
  src/stories/chart-elements/LineChart.stories.tsx
Labels: Type: Enhancement

#455 fix(tooltip): set max width for the tooltip
  src/components/util-elements/Tooltip/Tooltip.tsx
Labels: Type: Fix
