Repository tremorlabs/tremor, pull requests merged in 2023-09, with the labels that each got.

#643 feat: add weekStartsOn to DatePicker and DateRangePicker
  src/components/input-elements/Calendar/Calendar.tsx
  src/components/input-elements/DatePicker/DatePicker.tsx
  src/components/input-elements/DateRangePicker/DateRangePicker.tsx
  src/stories/input-elements/DatePicker.stories.tsx
  src/stories/input-elements/DateRangePicker.stories.tsx
Labels: Status: Review needed, Type: Enhancement, PR: Documentation Needed

#638 feat: improve readability of multiselect
  src/assets/XIcon.tsx
  src/components/input-elements/BaseInput.tsx
  src/components/input-elements/DatePicker/DatePicker.tsx
  src/components/input-elements/DateRangePicker/DateRangePicker.tsx
  src/components/input-elements/MultiSelect/MultiSelect.tsx
  src/components/input-elements/MultiSelect/MultiSelectItem.tsx
  src/components/input-elements/SearchSelect/SearchSelect.tsx
  src/components/input-elements/Select/Select.tsx
  src/stories/input-elements/MultiSelect.stories.tsx
  src/styles.css
Labels: PR: In Review

#639 fix: make Grid RSC compliant, again
  src/components/layout-elements/Grid/Grid.tsx
Labels: PR: In Review

#651 fix: Multiselect does not search with spaces
  src/components/input-elements/MultiSelect/MultiSelect.tsx
Labels: PR: In Review

#669 fix: Hides multiselect overflow-x scrollbar on Firefox
  src/components/input-elements/MultiSelect/MultiSelect.tsx
Labels: PR: In Review

#667 fix: Extra Margins in Tab and Button
  src/components/input-elements/Button/Button.tsx
  src/components/input-elements/Tabs/Tab.tsx
  src/stories/input-elements/Button.stories.tsx
  src/stories/input-elements/TabGroup.stories.tsx
Labels: PR: In Review

#649 fix: NumberInput does not pass event value through onChange
  src/components/input-elements/NumberInput/NumberInput.tsx
  src/stories/input-elements/NumberInput.stories.tsx
Labels: PR: In Review

#672 feat: Add on click event to ScatterChart
  src/components/chart-elements/ScatterChart/ScatterChart.tsx
  src/components/chart-elements/common/utils.ts
  src/stories/chart-elements/ScatterChart.stories.tsx
Labels: PR: Documentation Needed, PR: In Review

#674 fix: Improve styling in <Tabs> for variant solid
  src/components/input-elements/Tabs/Tab.tsx
  src/components/input-elements/Tabs/TabList.tsx
Labels: PR: In Review

#707 feat: On click events charts
  README.md
  src/components/chart-elements/AreaChart/AreaChart.tsx
  src/components/chart-elements/BarChart/BarChart.tsx
  src/components/chart-elements/DonutChart/DonutChart.tsx
  src/components/chart-elements/LineChart/LineChart.tsx
  src/components/chart-elements/ScatterChart/ScatterChart.tsx
  src/components/chart-elements/common/BaseChartProps.tsx
  src/components/chart-elements/common/ChartLegend.tsx
  src/components/chart-elements/common/ChartTooltip.tsx
  src/components/chart-elements/common/NoData.tsx
  src/components/chart-elements/common/index.ts
  src/components/chart-elements/common/utils.ts
  src/components/chart-elements/index.ts
  src/components/input-elements/Button/Button.tsx
  src/components/input-elements/Tabs/Tab.tsx
  src/components/input-elements/Tabs/TabList.tsx
  src/components/layout-elements/Divider/Divider.tsx
  src/components/text-elements/Legend/Legend.tsx
  src/components/vis-elements/ProgressBar/ProgressBar.tsx
  src/stories/chart-elements/AreaChart.stories.tsx
  src/stories/chart-elements/BarChart.stories.tsx
  src/stories/chart-elements/DonutChart.stories.tsx
  src/stories/chart-elements/LineChart.stories.tsx
  src/stories/chart-elements/ScatterChart.stories.tsx
  src/stories/chart-elements/helpers/testData.tsx
  src/stories/text-elements/Legend.stories.tsx
Labels: Status: In Beta, PR: In Review

#714 fix: Single data point on line and area charts
  src/components/chart-elements/AreaChart/AreaChart.tsx
  src/components/chart-elements/LineChart/LineChart.tsx
  src/components/chart-elements/common/utils.ts
  src/stories/chart-elements/AreaChart.stories.tsx
  src/stories/chart-elements/LineChart.stories.tsx
  src/stories/chart-elements/helpers/testData.tsx
Labels: PR: In Review

#710 fix: Remove unnecessary props on div
  src/components/input-elements/Calendar/Calendar.tsx
Labels: PR: In Review

#681 feat: enableClear option for SearchSelect component
  src/components/input-elements/SearchSelect/SearchSelect.tsx
  src/components/input-elements/Select/Select.tsx
Labels: PR: In Review

#589 feat: add displayFormat option for DatePicker
  src/components/input-elements/DatePicker/DatePicker.tsx
  src/components/input-elements/DateRangePicker/DateRangePicker.tsx
  src/components/input-elements/DateRangePicker/dateRangePickerUtils.tsx
  src/stories/input-elements/DatePicker.stories.tsx
  src/stories/input-elements/DateRangePicker.stories.tsx
Labels: PR: Documentation Needed, PR: In Review
