Repository tremorlabs/tremor, pull requests merged in 2023-10, with the labels that each got.

#719 feat: divider label with children
  src/components/layout-elements/Divider/Divider.tsx
  src/components/util-elements/Tooltip/Tooltip.tsx
  src/stories/layout-elements/Divider.stories.tsx
Labels: PR: In Review

#615 feat: Show/hide value in text input password
  src/assets/ArrowDownHeadIcon.tsx
  src/assets/ArrowDownIcon.tsx
  src/assets/ArrowDownRightIcon.tsx
  src/assets/ArrowUpHeadIcon.tsx
  src/assets/ArrowUpIcon.tsx
  src/assets/ArrowUpRightIcon.tsx
  src/assets/CalendarIcon.tsx
  src/assets/DoubleArrowLeftHeadIcon.tsx
  src/assets/DoubleArrowRightHeadIcon.tsx
  src/assets/ExclamationFilledIcon.tsx
  src/assets/EyeIcon.tsx
  src/assets/EyeOffIcon.tsx
  src/assets/LoadingSpinner.tsx
  src/assets/MinusIcon.tsx
  src/assets/PlusIcon.tsx
  src/assets/SearchIcon.tsx
  src/assets/index.ts
  src/components/input-elements/BaseInput.tsx
Labels: PR: In Review

#723 feat: barlist color improvement on dark mode
  src/components/vis-elements/BarList/BarList.tsx
Labels: PR: In Review

#725 fix: remove margin and add new default height on donut chart
  src/components/chart-elements/DonutChart/DonutChart.tsx
Labels: PR: In Review

#728 feat: custom tooltip for charts
  src/components/chart-elements/AreaChart/AreaChart.tsx
  src/components/chart-elements/BarChart/BarChart.tsx
  src/components/chart-elements/DonutChart/DonutChart.tsx
  src/components/chart-elements/LineChart/LineChart.tsx
  src/components/chart-elements/ScatterChart/ScatterChart.tsx
  src/components/chart-elements/common/BaseChartProps.tsx
  src/components/chart-elements/common/CustomTooltipProps.tsx
  src/lib/utils.tsx
  src/stories/chart-elements/AreaChart.stories.tsx
  src/stories/chart-elements/BarChart.stories.tsx
  src/stories/chart-elements/DonutChart.stories.tsx
  src/stories/chart-elements/LineChart.stories.tsx
  src/stories/chart-elements/ScatterChart.stories.tsx
Labels: PR: In Review

#745 fix: icon colors in dark mode
  src/components/icon-elements/Icon/styles.ts
Labels: PR: In Review

#761 feat: Switch component
  src/components/input-elements/Switch/Switch.tsx
  src/components/input-elements/Switch/index.ts
  src/components/input-elements/index.ts
  src/stories/input-elements/Switch.stories.tsx
  src/stories/input-elements/helpers/SimpleSwitch.tsx
Labels: PR: Documentation Needed, PR: In Review

#716 feat: Legend scroll
  src/assets/ChevronLeftFill.tsx
  src/assets/ChevronRightFill.tsx
  src/assets/index.ts
  src/components/chart-elements/AreaChart/AreaChart.tsx
  src/components/chart-elements/BarChart/BarChart.tsx
  src/components/chart-elements/LineChart/LineChart.tsx
  src/components/chart-elements/ScatterChart/ScatterChart.tsx
  src/components/chart-elements/common/BaseChartProps.tsx
  src/components/chart-elements/common/ChartLegend.tsx
  src/components/input-elements/Switch/Switch.tsx
  src/components/text-elements/Legend/Legend.tsx
  src/stories/chart-elements/AreaChart.stories.tsx
  src/stories/chart-elements/BarChart.stories.tsx
  src/stories/chart-elements/LineChart.stories.tsx
  src/stories/chart-elements/ScatterChart.stories.tsx
  src/stories/text-elements/Legend.stories.tsx
Labels: PR: Under Consideration

#778 feat: Textarea
  package.json
  pnpm-lock.yaml
  src/components/input-elements/Textarea/Textarea.tsx
  src/components/input-elements/Textarea/index.ts
  src/components/input-elements/index.ts
  src/stories/input-elements/TextArea.stories.tsx
  src/tests/input-elements/Textarea.test.tsx
Labels: PR: In Review

#759 feat: add spark charts (bar, line, area)
  src/components/spark-elements/SparkAreaChart/SparkAreaChart.tsx
  src/components/spark-elements/SparkAreaChart/index.ts
  src/components/spark-elements/SparkBarChart/SparkBarChart.tsx
  src/components/spark-elements/SparkBarChart/index.ts
  src/components/spark-elements/SparkLineChart/SparkLineChart.tsx
  src/components/spark-elements/SparkLineChart/index.ts
  src/components/spark-elements/common/BaseSparkChartProps.tsx
  src/components/spark-elements/index.ts
  src/stories/chart-elements/helpers/testData.tsx
  src/stories/spark-elements/SparkAreaChart.stories.tsx
  src/stories/spark-elements/SparkBarChart.stories.tsx
  src/stories/spark-elements/SparkLineChart.stories.tsx
  src/stories/spark-elements/helpers/ExampleCard.tsx
Labels: PR: In Review
